#!/bin/zsh
## Change screen brightness on computers where linux
## fails to detect function keys for it.
## More dynamic than /sys/class/backlight/..->

config=${XDG_CONFIG_DIR:-$HOME/.config}/.brightness
output='setpci -s 00:02.0 F4.B='
current=$(cat $config|awk '{print $5}'|cut -c6,7)
argument="5"

brightness_up() {
	if [ $current = FF ]; then
		return
	fi
	if [ $current = 95 ]; then
		NEW=FF
		echo $output$NEW > $config
		sh $config
	else
		NEW=$(expr $current + $argument)
		echo $output$NEW > $config
		sh $config
	fi
}

brightness_down() {
	if [ $current = 5 ]; then
		return
	fi
	if [ $current = FF ]; then
		NEW=95
		echo $output$NEW > $config
		sh $config
	else
		NEW=$(expr $current - $argument)
		echo $output$NEW > $config
		sh $config
	fi
}

brightness_max() {
  NEW=FF
  echo $output$NEW > $config
  sh $config
}

case "$1" in
	'-u'|'--up')
	brightness_up
	;;
	'-d'|'--down')
	brightness_down
	;;
  '-m'|'--max')
  brightness_max
  ;;
esac
