#!/bin/zsh
# milomouse <vincent[at]fea.st>
# NOTE: Easily choose different window-managers on startup.
#       This is just an experiment and is pretty useless.

# commands you wish to run on startup.
putinx() {
cat << EOF
banished=$HOME/.config/.mouv
[ ! -f $banished ] || rm -f $banished
xmodmap -e "keycode 133 = Alt_L"
xmodmap -e "keycode 64 = Super_L"
xbindkeys &
display -window root -geometry 1366x768! $HOME/foto/wall/careview.jpg
synap
$WM
EOF
}

if [[ -n $(ps -a|grep xinit) ]]; then
  echo "Already running X."
  exit 1
else
  # define your window manager options here
  if [ "$1" = "-r" ]; then
    WM="exec ratpoison >>/dev/null"
  elif [ "$1" = "-i" ]; then
    WM="exec ion3plus -noerrorlog >>/dev/null"
  elif [ "$1" = "-m" ]; then
    WM="exec musca -s $XDG_CONFIG_DIR/musca/musca_start >>/dev/null"
  fi
  if [ ! -n "$1" ]; then
    startx -- -dpi 120
  else
    [ ! -f ~/.xinitrc ] || rm -f ~/.xinitrc
    putinx > ~/.xinitrc
    startx -- -dpi 120
  fi
fi
