#!/bin/zsh
# milomouse <vincent[at]fea.st>
# NOTE: Banish mouse and disable touchpad, also undo this.

cords=${XDG_CONFIG_HOME:-$HOME/.config}/.mouv

# mouse stuff:
if [ -f $cords ]; then
  xdotool mousemove $(<$cords)
  rm $cords
else
  current=$(xdotool getmouselocation |sed 's/:/ /g'|cut -d " " -f 2,4)
  print $current >> $cords
  xdotool mousemove $(xdpyinfo|grep dimensions|awk '{print $2}'|tr 'x' ' ')
fi

# touchpad:
if [ $(synclient -l|grep TouchpadOff|awk '{print $3}') = 0 ]; then
  synclient TouchpadOff=1
else
  synclient TouchpadOff=0
fi
