#!/bin/zsh
# cron job: if: online > imap > if: ratpoison > notify new.
sleep 20
if [ `ls /var/run/daemons|grep network` ]; then
  offlineimap -u Noninteractive.Quiet
  if [ `ps -a|grep ratpoison|awk '{print $4}'` ]; then
      local INFO=$(ls -l /home/milo/mail/*/*/new|\
       grep $HOST|cat -n|awk '{print $1}'|tail -1)
      ratpoison -c "echo >>> offlineIMAP >>> $INFO new emails"
      sleep 10
      ratpoison -c "echo >>> offlineIMAP >>> $INFO new emails"
      sleep 10
      ratpoison -c "echo >>> offlineIMAP >>> $INFO new emails"
  fi
fi
