#!/bin/zsh
# cron job to check for new emails then report to ratpoison if found in X.
# quickly made for personal use, if you use this change user, maildir, etc

if [ `ls /var/run/daemons|grep network` = network ]; then
  if [ `ps -a|grep xinit|awk '{print $4}'` ]; then
    if [ `ps -a|grep ratpoison|awk '{print $4}'` ]; then
      INFO=$(ls -l /home/milo/mail/*/*/new|\
       grep $HOST|cat -n|awk '{print $1}'|tail -1)
      offlineimap
      ratpoison -c "echo >>> offlineIMAP >>> $INFO new emails"
      sleep 10
      ratpoison -c "echo >>> offlineIMAP >>> $INFO new emails"
      sleep 10
      ratpoison -c "echo >>> offlineIMAP >>> $INFO new emails"
    fi
  else
    sleep 45
    offlineimap
  fi
fi
