#!/bin/bash
if [ "$USER" = "root" ]; then
  maybe_mirrors=$(w3m -dump 'https://www.archlinux.de/?page=MirrorStatus;orderby=lastsync;sort=1'|\
    grep "tp:/"|head -n 10|awk '{print $1}'|sed "s/$/\$repo\/os\/`arch`/")
  bad_mirrors=$(w3m -dump 'https://www.archlinux.de/?page=MirrorStatus;orderby=avgtime;sort=1'|\
    grep "tp:/"|head -n 10|awk '{print $1}'|sed "s/$/\$repo\/os\/`arch`/")
  good_mirrors=()

  for i in $maybe_mirrors; do
    if grep -q $i <<< $bad_mirrors; then
      :
    else
       good_mirrors=( "${good_mirrors[@]}" "$i\n" )
    fi
  done

  good_mirrors_ranked=$(echo -e "${good_mirrors[@]}" | grep -vi i686 | grep -vi archlinux.org |\
    sed 's/^/Server = /;s/$//' | head -n 5 | rankmirrors -n 5 - )

  if [ -f /etc/pacman.d/mirrorlist ]; then
    mv /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist-old
  fi
    echo "$good_mirrors_ranked" > /etc/pacman.d/mirrorlist
    cat /etc/pacman.d/mirrorlist
  else
    echo "User \"$USER\" does not have the required priviledges to run this script."
fi
