#!/bin/sh
# Depends on "xdotool".
#
# Description: Move the mouse to the far corner,
# and bring it back by issuing the same command.
#
# Todo: Find a way to discover screen resolution
# and disable/enable"Alps GlidePoint" touchpad.

MCORD=$HOME/.config/.mouv

if [ -f $MCORD ]; then
	xdotool mousemove $(cat $MCORD)
	rm $MCORD
else
	CURR=$(xdotool getmouselocation |tr 'xy:screen' ' '|cut -c3,4,5,6,9,10,11,12)
	`echo $CURR >> $MCORD`
	xdotool mousemove 1366 0
fi
