#!/bin/bash

# ossvol is a simple script to manage oss volume levels and muting.
# Script by: Daniel J Griffiths <ghost1227@archlinux.us>

# Configure stuff
VOLSTORE=~/.config/.volume
CHANNEL="vmix0-outvol"
ARGUMENT=$2

# You shouldn't have to edit below here.
err() {
	echo "$1"
	exit 1
}

usage() {
	echo "usage: ossvol [option] [argument]"
	echo
	echo "Options:"
	echo "     -i, --increase - increase volume by [argument]"
	echo "     -d, --decrease - decrease volume by [argument]"
	echo "     -t, --toggle   - toggle mute on and off"
	echo "     -h, --help     - display this"
	exit
}


toggle() {
	if [ -f $VOLSTORE ]; then
		ossmix $CHANNEL `cat $VOLSTORE`
		rm $VOLSTORE
oss=`ossmix|grep outvol|awk '{print $4}'`
if [ $oss == 0.0 ]; then
	ratpoison -c "echo >>> Vol:  MUTED"
    else
	ratpoison -c "echo >>> Vol: $oss\dB"
fi
	else
		VOLUME=$(ossmix $CHANNEL | awk '{print $10}' | awk -F : '{print $1}')
		ossmix $CHANNEL 0
#		echo $VOLUME &gt; $VOLSTORE
		`echo $VOLUME >> $VOLSTORE`
oss=`ossmix|grep outvol|awk '{print $4}'`
if [ $oss == 0.0 ]; then
	ratpoison -c "echo >>> Vol:  MUTED"
    else
	ratpoison -c "echo >>> Vol: $oss\dB"
fi
	fi
}

increase() {
	if [ -f $VOLSTORE ]; then
		TMPVOL=`cat $VOLSTORE`
		NEWVOL=`expr $TMPVOL + $ARGUMENT`
		ossmix $CHANNEL +$NEWVOL
		rm $VOLSTORE
	else
		ossmix $CHANNEL +$ARGUMENT
	fi
}

decrease() {
	if [ -f $VOLSTORE ]; then
		TMPVOL=`cat $VOLSTORE`
		NEWVOL=`expr $TMPVOL - $ARGUMENT`
		ossmix $CHANNEL -- -$NEWVOL
		rm $VOLSTORE
	else
		ossmix $CHANNEL -- -$ARGUMENT
	fi
}

case "$1" in
	'-i'|'--increase')
	increase
	;;
	'-d'|'--decrease')
	decrease
	;;
	'-t'|'--toggle')
	toggle
	;;
	''|'-h'|'--help')
	usage
	;;
	*)
	err "Unrecognized option \`$1', see ossvol --help"
	;;
esac
