#!/bin/zsh
# Batch rename files within folder.

if [ -z $1 ];then
	echo Give target directory;
	exit 0;
fi

find "$1" -depth -name '*' | while read file ; do
	directory=$(dirname "$file")
	oldfilename=$(basename "$file")
	newfilename=$(echo "$oldfilename" | tr 'A-Z' 'a-z')
	#newfilename=$(echo "$oldfilename" | tr 'A-Z' 'a-z' | tr ' ' '_' | sed s/_-_/_/g)
	#newfilename=$(echo "$oldfilename" | tr 'A-Z' 'a-z' | tr ' ' '_' | sed s/dailymotion_-_//g)
	#newfilename=$(echo "$oldfilename" | tr 'A-Z' 'a-z' | tr ' ' '_' | sed s/chowder_-_//g)
	#newfilename=$(echo "$oldfilename" | sed s/_-_/_/g)
	#newfilename=$(echo "$oldfilename" | tr ' ' '_')
	#newfilename=$(echo "$oldfilename" | tr '_' '-')
	if [ "$oldfilename" != "$newfilename" ]; then
		mv -i "$directory/$oldfilename" "$directory/$newfilename"
		echo $'\E[0;35m'"$directory/"$'\E[0;34m'"$oldfilename"$'\E[1;30m' "==>" $'\E[0;35m'"$directory/"$'\E[1;34m'"$newfilename"$'\E[0m'
	fi
done
exit 0
