#!/bin/zsh
# Banish mouse and disable touchpad, also undo this.
# Requires: xdotool, xdpyinfo (xorg-utils), synclient (xf86-input-synaptics)
# TODO: find better way to do this..

MCORD=${XDG_CONFIG_HOME}/.mouv

if [ -f $MCORD ]; then
   xdotool mousemove $(cat $MCORD)
   rm $MCORD
else
   CURR=$(xdotool getmouselocation |sed 's/:/ /g'|cut -d " " -f 2,4)
   echo $CURR >> $MCORD
   xdotool mousemove $(xdpyinfo|grep dimensions|awk '{print $2}'|tr 'x' ' ')
fi

if [ $(synclient -l|grep TouchpadOff|awk '{print $3}') = 0 ]; then
   synclient TouchpadOff=1
else
   synclient TouchpadOff=0
fi
