#!/bin/zsh
# milomouse <vincent[at]fea.st>
# Banish mouse and disable touchpad, also undo this.

MCORD=$HOME/.config/.mouv

if [ -f $MCORD ]; then
   xdotool mousemove $(cat $MCORD)
   rm $MCORD
else
   CURR=$(xdotool getmouselocation |sed 's/:/ /g'|cut -d " " -f 2,4)
   echo $CURR >> $MCORD
   xdotool mousemove $(xdpyinfo|grep dimensions|awk '{print $2}'|tr 'x' ' ')
fi

if [ `synclient -l|grep TouchpadOff|awk '{print $3}'` = 0 ]; then
   synclient TouchpadOff=1
else
   synclient TouchpadOff=0
fi
