#!/bin/zsh
unsetopt nomatch functionargzero
  setopt cshjunkieloops

# REGULAR COLORS       ; # BOLD COLORS:
local c0=$'\033[0;30m' ; local c0b=${c1/0;/1;}
local c1=$'\033[0;31m' ; local c1b=${c1/0;/1;}
local c2=$'\033[0;32m' ; local c2b=${c2/0;/1;}
local c3=$'\033[0;33m' ; local c3b=${c3/0;/1;}
local c4=$'\033[0;34m' ; local c4b=${c4/0;/1;}
local c5=$'\033[0;35m' ; local c5b=${c5/0;/1;}
local c6=$'\033[0;36m' ; local c6b=${c6/0;/1;}
local c7=$'\033[0;37m' ; local c7b=${c7/0;/1;}
local c8=$'\033[0;38m' ; local c8b=${c8/0;/1;}
local c9=$'\033[1;39m' ; local c9b=${c9/0;/1;}
local cn=$'\033[0m'

# VOLUME BAR (for OSS):
function _volume() {
  for i in $(print ${${$(ossmix | grep outvol)[-2][1,2]// }//.});
    repeat $i; print -n "\033[0;31m|" ; end
    repeat $(( 25 - $i )); print -n "\033[0;35m|" ; end
    print $c4" $i/25"$c4b dB$cn
  end
}
# CURRENT MIXER SETTINGS (for OSS):
function _mixer() {
  if [[ $(print ${$(ossmix | grep er.mo)[-1]}) =~ mix2 ]]; then
    print $c7b\- PC Speaker -$cn
  else
    print $c7b\- Headphones -$cn
  fi
}
# CURRENT MEDIA FILE (for MIFO):
function _playing() {
  local _media="$(mifo --raw)"
  if [[ ${#${(@f)_media}} -gt ${_count} ]]; then
    print $c4b${${_media/$_media:e/}[1,${_count}]}$c5b...$c7b$_media:e$cn
  else
    print $c4b$_media:r$c5b.$c7b$_media:e
  fi
}

# CONSOLE vs X DISPLAY:
local _v="_______________________________________________________________"
local _v2="===================================================================="
local _v3=${_v}
if test -z ${DISPLAY};
then local _v=${_v//_/ } ; local _v3="${_v}     " ; local _c=${c0b} ; local _count=145 \
local _v0="
$_v                                 ▐███▓ ▐██▌▐  ▀             ▓                      ▓█▄▄
$_v                                  ███▌▀█▄▄▀                  ▓ ▓                       ▀▓▄▄
$_v                                  ███░  ▓             ▓      ▐▌▐ ▄ ▄▄▓▓█████▄▄▄            ▀█▄▄
$_v                                  ▐██▓  ▐              ▌   ▓ ▐▓▓▓██▀▀         ▀▀▀▓▓▄▄          ▀▀▓▄
$_v                                   ███░                ▌   ▐  ▓██▀                  ▀▀▀▓▓▄▄      ▄▄▓▀ 
$_v                                   ▐██▓  ▓░                ▓  ██                           ▀▀▀▀▀▀
$_v                                    ▐██  █▓░          ▐    ▒ ▐█▌
$_v                                     ▓██▄██▓          ▓   ░  ▐▓
$_v                                    ▓██████▌         ▐▌      ▓
$_v                                   ░███████         ██      ▐░
$_v                                   ▓███████    ▐   ███      ▓
$_v                                   ▓███▓████▄▄▄▓ ▄███▓     ▐▌
$_v                                   ▓███▓██████▓▌ ▐███▓▀▀▄  █
$_v                                  ▐███▌▐▓██████▓  ███▌    ▐"
else local _v= ; local _v2= ; local _v3= ; local _v0= ; local _c=${c0}; local _count=80 ; \
print $_v2$c7======================================================================================================$cn ; \
local _v0="
$_v              $c7▄▄███▄$cn             ▐███▓ ▐██▌▐  ▀             ▓                      ▓█▄▄
$_v            $c7▄██▓   ▓▓$cn             ███▌▀█▄▄▀                  ▓ ▓                       ▀▓▄▄
$_v           $c7███▀$cn                   ███░  ▓             ▓      ▐▌▐ ▄ ▄▄▓▓█████▄▄▄            ▀█▄▄
$_v          $c7▐██▓                   █$cn▐██▓  ▐              ▌   ▓ ▐▓▓▓██▀▀         ▀▀▀▓▓▄▄          ▀▀▓▄
$_v          $c7▐██░                  █░$cn ███░                ▌   ▐  ▓██▀                  ▀▀▀▓▓▄▄      ▄▄▓▀ 
$_v          $c7██▓░                ██░$cn  ▐██▓  ▓░                ▓  ██                           ▀▀▀▀▀▀"
fi

# REAL-TIME OUTPUT:
<< EOF
$(_volume) $(_mixer)$c4b ($(print ${$(ossmix | grep jack.int-speaker.mode)[-1]//\)}))$cn $_v3                     $c9$(command date +%a" "%Y-%_m-%_d$c7/%_j"$cn "%R)
$_v2$c7======================================================================================================$cn
 "$(printf $c7b)I think the Ph.D behind my name means I know a little something about dinosaurs.$cn" - Land of the Lost

$_v                                   ▄▄    ▄▓▄         $c7▄████▄$cn    
$_v                                  ▓█▓█▄▓████        $c7██▓░░▀█  ▄▄███▄$cn 
$_v                                  ▓▌■▓███▀█▌      $c7▄██░    █▄███████▌    ▄▄███▄      ▄▄      ▄▄$cn
$_v                                 ▄██████▌■░▓▌    $c7██▓      ███▀ ▓████  ▄██▓   ▓▓    ██▓     ▐█▓$cn
$_v                                 ▓██▓▓▓▀   ░▓  $c7▄██░       ██▌  ▐███▌ ███▀          ██▓     ██▓$cn
$_v                                ▐▐▓▓▀▀ ▄▄███░▓$c7██▓   ▄█▌  ▐██  ▄███▀ ▐██▓          ▐██▓     ██▓$cn
$_v                                ▌ ▀ ▄▄█▀▌▐▄▌▓$c7██▒   ▓██▌  ▐██████▀   ▐██░          ██▓▓     ██▓$cn
$_v                                ▓ ▄█▓▌▐▄███▌█$c7█░          ████████▄  ███░          ███████████▓$cn
$_v                                ▀█▓ ████████$c7█▒   ▐████   ███▌▀▓████▓███▓       ▄  ██▓      ██▓$cn
$_v                                 ▓▒ ▐█▓▒██▌$c7█▒   ▐█████   ███    ▀███████▓     ▐█  ██▓      ██▓$cn
$_v                                 █▓▒ █▓▒▓█ ▌    ██████▄  $c7███      ▀███████▄▄▄▓▓█████▓      ██▓$cn
$_v                                 ███ ▐█▓▒█▀▓▄▄▓▀      ▀▀▓▄$c7▀▀$cn ▄▄▄▄▓▓▓█▓█▓██$c7█████████▓       ▓██$cn
$_v                                 ███▓ ▐█▓█▌▐▀  ▄▓         ▀█▓▓▀▀▀          ▀▀██████░        $c7▓██$cn$_v0
$_v2$c7=======================================================================================$c4 LAST LOGINS$c7 ==$c4b
$(command last -xad5 | head -5)$cn
$_v2$c7===========================================================================================$c4 DETAILS$c7 ==$cn
;;$c5 Hostname$c7:$cn $c7${USER}$cn@$c1b$(uname -n)$cn
;;$c5 Runlevel$c7:$cn ${RUNLEVEL}
;;$c5 Kernel$_c..$c7:$cn $(uname -r)$cn
;;$c5 CmdLine$_c.$c7:$cn ${${CMDLINE//BOOT_IMAGE=${BOOT_IMAGE} /}//root=${root} /}$cn
;;$c5 LoadAvg$_c.$c7:$cn $(print ${${$(</proc/loadavg)[1,3]}//0/$c7\o$cn})$cn
;;$c5 Memory$_c..$c7:$cn $(command free -m | awk 'NR==2 {print $3" / "$2}')$c7 MB$cn
;;$c5 Playing$_c.$c7: $(_playing)$cn
$_v2$c7======================================================================================================$cn
EOF
unsetopt cshjunkieloops
  setopt nomatch functionargzero
