#! /bin/sh

########################
## Initiate Desktops: ##
########################
FIRST_DESK=1
REMAINING_DESKS="$(seq 2 9) 0"
bspc desktop Desktop01 -n $FIRST_DESK
bspc monitor --add-desktops $REMAINING_DESKS
bspc monitor --pad 14 0 0 0

########################
## Initiate Rules:    ##
########################
bspc rule --add sxiv --floating
bspc rule --add gcolor2 --floating
bspc rule --add luakit --desktop 3 --follow
bspc rule --add Gimp --desktop 8 --floating
bspc rule --add pavucontrol --desktop 0 --follow --floating
bspc rule --add xfontsel --floating
bspc rule --add fontforge --desktop 7 --follow

########################
## Initiate Settings: ##
########################
#+ focus
bspc config history_aware_focus true
#+ splitting
bspc config split_ratio         0.50
#+ decoration
bspc config border_width        4
bspc config window_gap          5
bspc config borderless_monocle  true
bspc config gapless_monocle     false
#+ colors
bspc config focused_border_color         "#949494"
bspc config normal_border_color          "#191919"
bspc config active_border_color          "#5C5955"
bspc config focused_locked_border_color  "#00C7D8"
bspc config normal_locked_border_color   "#708D8F"
bspc config active_locked_border_color   "#808C8D"
bspc config urgent_border_color          "#93F388"
bspc config presel_border_color          "#222222"
