#! /bin/sh

## Initiate workspaces:
FIRST_DESK=1
REMAINING_DESKS="$(seq 2 9) 0"
bspc rename Desktop01 $FIRST_DESK
bspc add $REMAINING_DESKS
bspc pad LVDS 14 0 0 0

## Rules:
bspc rule sxiv floating
bspc rule gcolor2 floating
bspc rule luakit 3 follow
bspc rule Gimp 8 floating
bspc rule pavucontrol 0 follow
bspc rule pavucontrol floating

## Settings:
#+ focus
bspc set history_aware_focus true
bspc set focus_by_distance   false
#+ splitting
bspc set split_ratio         0.53
#+ decoration
bspc set border_width        4
bspc set window_gap          5
bspc set borderless_monocle  true
bspc set gapless_monocle     true
#+ colors
bspc set focused_border_color         "#6F7277"
bspc set active_border_color          "#5C5955"
bspc set normal_border_color          "#34322E"
bspc set focused_locked_border_color  "#D64C8A"
bspc set active_locked_border_color   "#A363B2"
bspc set normal_locked_border_color   "#4F3755"
bspc set urgent_border_color          "#00C7D8"
bspc set presel_border_color          "#222222"
