#! /bin/zsh
###############################################
## locate: ${XDG_CONFIG_HOME}/bspwm/bspwmrc  ##
## author: milomouse (github.com/milomouse)  ##
## detail: startup configuration for `bspwm' ##
###############################################

########################
## Initiate Desktops: ##
########################
bspc desktop ^1 -n I
bspc monitor -a II III IV V VI VII VIII IX X
bspc config top_padding 14

########################
## Restore Session:   ##
########################
if [[ -s "$BSPWM_TREE" ]] {
  bspc restore --tree "$BSPWM_TREE"
  rm "$BSPWM_TREE"
} else { bspc control --adopt-orphans }

if [[ -s "$BSPWM_HISTORY" ]] {
  bspc restore --history "$BSPWM_HISTORY"
  rm "$BSPWM_HISTORY"
}

########################
## Initiate Rules:    ##
########################
bspc rule -a gcolor2 --floating --center
bspc rule -a sxiv --floating --center
bspc rule -a xfontsel --floating --center
bspc rule -a lxappearance --floating --center
bspc rule -a pavucontrol -d ^10 --follow --floating --center
bspc rule -a dwb -d ^3
bspc rule -a luakit -d ^3
bspc rule -a Firefox -d ^4
bspc rule -a gimp -d ^8 --floating

########################
## Initiate Settings: ##
########################
##+ focus
bspc config history_aware_focus true
##+ splitting
bspc config split_ratio         0.50
##+ decoration
bspc config border_width        4
bspc config window_gap          4
bspc config borderless_monocle  true
bspc config gapless_monocle     false
##+ colors
bspc config focused_border_color         "#242424"
bspc config normal_border_color          "#141414"
bspc config active_border_color          "#5C5955"
bspc config focused_locked_border_color  "#00C7D8"
bspc config normal_locked_border_color   "#708D8F"
bspc config active_locked_border_color   "#808C8D"
bspc config urgent_border_color          "#93F388"
bspc config presel_border_color          "#101010"
