#! /bin/zsh
###############################################
## locate: ${XDG_CONFIG_HOME}/bspwm/bspwmrc  ##
## author: milomouse (github.com/milomouse)  ##
## detail: startup configuration for `bspwm' ##
###############################################

########################
## Initiate Desktops: ##
########################
bspc monitor --reset-desktops I II III IV V VI VII VIII IX X
for x ( III IV X ) { bspc desktop ${x} --layout monocle }
bspc config top_padding 18
for x ( left right bottom ) { bspc config ${x}_padding -8 }

########################
## Restore Session:   ##
########################
if [[ -s "$BSPWM_TREE" ]] {
  bspc restore --tree "$BSPWM_TREE"
  rm "$BSPWM_TREE"
} else { bspc control --adopt-orphans }

if [[ -s "$BSPWM_HISTORY" ]] {
  bspc restore --history "$BSPWM_HISTORY"
  rm "$BSPWM_HISTORY"
}

if [[ -s "$BSPWM_STACK" ]] {
  bspc restore --stack "$BSPWM_STACK"
  rm "$BSPWM_STACK"
}

########################
## Initiate Rules:    ##
########################
bspc rule -a gcolor2 floating=true center=true
bspc rule -a sxiv floating=true center=true
bspc rule -a xfontsel floating=true center=true
bspc rule -a lxappearance floating=true center=true
bspc rule -a Dwb desktop=III
bspc rule -a Firefox desktop=IV
bspc rule -a gimp desktop=VIII floating=true
bspc rule -a pavucontrol desktop=X follow=true floating=true center=true

########################
## Initiate Settings: ##
########################
##+ focus
bspc config history_aware_focus true
##+ splitting
bspc config split_ratio         0.50
##+ decoration
bspc config border_width        5
bspc config window_gap          8
bspc config borderless_monocle  true
bspc config gapless_monocle     false
##+ colors
bspc config focused_border_color         "#242424"
bspc config normal_border_color          "#141414"
bspc config active_border_color          "#5C5955"
bspc config focused_locked_border_color  "#00C7D8"
bspc config normal_locked_border_color   "#708D8F"
bspc config active_locked_border_color   "#808C8D"
bspc config urgent_border_color          "#93F388"
bspc config presel_border_color          "#101010"

