#!/bin/zsh
# LEFT: info bar to the right of xmonad's:
while true; do
  echo " ^fg(#a488d9)| ^fg(#515056)#$(lsw|grep -v 'gcolor2\|Vimperator\|GLiv\| - Downloads'|wc -l) \
^fg(#a488d9)| ^fg()$(cat /proc/loadavg|sed 's/ [0-9]\/.*$//;s/\./'"^fg(#5f656b)"'&'"^fg()"'/g') ^fg(#a488d9)| ^fg()\
$(df -h|grep "sda2\|sda5\|sda3"|awk '{print "^fg(#5f656b)"$4"^fg(#050505)""""|^fg(#444)"$5" "}'|tr -d '\n')"\
"^fg(#a488d9)| ^fg(#515056)@fea.st: ^fg()$(ls -1 /home/milo/mail/FastMail/*/new|sed 's|/.*$||'|tr '\n' ' '|wc -w)" \
"^fg() ^fg(#a488d9)>""^fg(#007b8c)>""^fg(#444444)>"
  sleep 1
done | dzen2 -u -x '237' -y '0' -h '13' -w '425' -ta 'l' -bg '#161616' -fg '#8c8b8e' -fn '-*-fixed-medium-r-normal-*-10-*-*-*-*-*-*-*' &
# CENTER: current media playing:
while true; do
  mifo -ad
  sleep 1
done | dzen2 -u -x '662' -y '0' -h '13' -w '460' -ta 'r' -bg '#161616' -fg '#8c8b8e' -fn '-*-fixed-medium-r-normal-*-10-*-*-*-*-*-*-*' &
# RIGHT: oss volume, date:
while true; do
  echo "^fg(#a488d9)>""^fg(#007b8c)>""^fg(#444444)> ^fg()$(ossmix|grep outvol|awk '{print $4}')^fg(#5f656b)dB ^fg(#a488d9) | ^fg()$(date '+%Y^fg(#444).^fg()%m^fg(#444).^fg()%d^fg(#007b8c)/^fg(#5f656b)%a ^fg(#a488d9)| ^fg()%H^fg(#444):^fg()%M^fg(#444):^fg()%S') "
  sleep 1
done | dzen2 -u -x '1122' -y '0' -h '13' -w '244' -ta 'r' -bg '#161616' -fg '#8c8b8e' -fn '-*-fixed-medium-r-normal-*-10-*-*-*-*-*-*-*' &
