(("3" 1 T NIL :CLASS "MPlayer" :INSTANCE "xv" :TITLE NIL :ROLE NIL)
 ("3" 1 T NIL :CLASS "MPlayer" :INSTANCE "xv" :TITLE NIL :ROLE NIL)
 ("6" 0 T T :CLASS "Gliv" :INSTANCE "gliv" :TITLE NIL :ROLE NIL)
 ("3" 0 T T :CLASS "luakit" :INSTANCE "luakit" :TITLE NIL :ROLE NIL))