(("6" 0 T T :CLASS "Pysol" :INSTANCE "pySol #2" :TITLE NIL :ROLE NIL)
 ("6" 0 T T :CLASS "xskat" :INSTANCE "xskat" :TITLE NIL :ROLE NIL)
 ("3" 0 T T :CLASS "luakit" :INSTANCE "luakit" :TITLE NIL :ROLE NIL)
 ("6" 0 T T :CLASS "Ossxmix")
 ("3" 1 T NIL :CLASS "MPlayer" :INSTANCE "xv" :TITLE NIL :ROLE NIL))