-- This file has been generated by Ion. Do not edit.
return {
    ["date"] = {
        ["date_format"] = "%a %Y-%m-%d %H:%M",
    },
    ["exec"] = {
        ["oval"] = {
            ["program"] = "/home/milo/code/shell/ready/oval",
            ["retry_delay"] = 1000,
        },
    },
    ["load"] = {
        ["critical_threshold"] = 2,
        ["important_threshold"] = 0,
    },
    ["mail"] = {
    },
}

