-- This file has been generated by Ion. Do not edit.
return {
    [0] = {
        ["type"] = "WRootWin",
        ["name"] = "WRootWin",
        ["managed"] = {
            [1] = {
                ["type"] = "WGroupWS",
                ["name"] = "1.WORK",
                ["hidden"] = true,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1366,
                    ["h"] = 768,
                },
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<2>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1366,
                            ["h"] = 768,
                        },
                        ["split_tree"] = {
                            ["tls"] = 10,
                            ["tl"] = {
                                ["type"] = "WSplitST",
                            },
                            ["dir"] = "vertical",
                            ["brs"] = 758,
                            ["br"] = {
                                ["tls"] = 794,
                                ["tl"] = {
                                    ["tls"] = 378,
                                    ["tl"] = {
                                        ["regparams"] = {
                                            ["mode"] = 1,
                                            ["type"] = "WFrame",
                                            ["name"] = "WFrame<4>",
                                            ["managed"] = {
                                            },
                                        },
                                        ["type"] = "WSplitRegion",
                                    },
                                    ["dir"] = "vertical",
                                    ["brs"] = 380,
                                    ["br"] = {
                                        ["regparams"] = {
                                            ["mode"] = 1,
                                            ["type"] = "WFrame",
                                            ["name"] = "WFrame<6>",
                                            ["managed"] = {
                                            },
                                        },
                                        ["type"] = "WSplitRegion",
                                    },
                                    ["type"] = "WSplitSplit",
                                },
                                ["dir"] = "horizontal",
                                ["brs"] = 572,
                                ["br"] = {
                                    ["tls"] = 286,
                                    ["tl"] = {
                                        ["regparams"] = {
                                            ["mode"] = 1,
                                            ["type"] = "WFrame",
                                            ["name"] = "WFrame",
                                            ["managed"] = {
                                            },
                                        },
                                        ["type"] = "WSplitRegion",
                                    },
                                    ["dir"] = "vertical",
                                    ["brs"] = 472,
                                    ["br"] = {
                                        ["tls"] = 258,
                                        ["tl"] = {
                                            ["regparams"] = {
                                                ["mode"] = 1,
                                                ["type"] = "WFrame",
                                                ["name"] = "WFrame<2>",
                                                ["managed"] = {
                                                },
                                            },
                                            ["type"] = "WSplitRegion",
                                        },
                                        ["dir"] = "vertical",
                                        ["brs"] = 214,
                                        ["br"] = {
                                            ["regparams"] = {
                                                ["mode"] = 1,
                                                ["type"] = "WFrame",
                                                ["name"] = "WFrame<3>",
                                                ["managed"] = {
                                                },
                                            },
                                            ["type"] = "WSplitRegion",
                                        },
                                        ["type"] = "WSplitSplit",
                                    },
                                    ["type"] = "WSplitSplit",
                                },
                                ["type"] = "WSplitSplit",
                            },
                            ["type"] = "WSplitSplit",
                        },
                    },
                },
                ["level"] = 0,
            },
            [2] = {
                ["type"] = "WGroupWS",
                ["name"] = "2.TEMP",
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1366,
                    ["h"] = 768,
                },
                ["switchto"] = true,
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1366,
                            ["h"] = 768,
                        },
                        ["split_tree"] = {
                            ["tls"] = 10,
                            ["tl"] = {
                                ["type"] = "WSplitST",
                            },
                            ["dir"] = "vertical",
                            ["brs"] = 758,
                            ["br"] = {
                                ["regparams"] = {
                                    ["mode"] = 1,
                                    ["type"] = "WFrame",
                                    ["name"] = "WFrame<14>",
                                    ["managed"] = {
                                        [1] = {
                                            ["type"] = "WClientWin",
                                            ["level"] = 0,
                                            ["windowid"] = 8388750,
                                            ["switchto"] = true,
                                            ["sizepolicy"] = "full",
                                            ["geom"] = {
                                                ["y"] = 17,
                                                ["x"] = 6,
                                                ["w"] = 1354,
                                                ["h"] = 735,
                                            },
                                            ["checkcode"] = 1,
                                        },
                                    },
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["type"] = "WSplitSplit",
                        },
                    },
                },
                ["level"] = 0,
            },
            [3] = {
                ["type"] = "WGroupWS",
                ["name"] = "3.BROWSE",
                ["hidden"] = true,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1366,
                    ["h"] = 768,
                },
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<1>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1366,
                            ["h"] = 768,
                        },
                        ["split_tree"] = {
                            ["tls"] = 491,
                            ["tl"] = {
                                ["regparams"] = {
                                    ["mode"] = 1,
                                    ["type"] = "WFrame",
                                    ["name"] = "WFrame<1>",
                                    ["managed"] = {
                                    },
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["dir"] = "vertical",
                            ["brs"] = 277,
                            ["br"] = {
                                ["tls"] = 683,
                                ["tl"] = {
                                    ["regparams"] = {
                                        ["type"] = "WFrame",
                                        ["name"] = "WFrame<10>",
                                        ["saved_h"] = 234,
                                        ["mode"] = 1,
                                        ["managed"] = {
                                        },
                                        ["saved_y"] = 566,
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["dir"] = "horizontal",
                                ["brs"] = 683,
                                ["br"] = {
                                    ["regparams"] = {
                                        ["saved_w"] = 640,
                                        ["type"] = "WFrame",
                                        ["name"] = "WFrame<5>",
                                        ["saved_x"] = 640,
                                        ["saved_h"] = 234,
                                        ["mode"] = 1,
                                        ["managed"] = {
                                        },
                                        ["saved_y"] = 566,
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["type"] = "WSplitSplit",
                            },
                            ["type"] = "WSplitSplit",
                        },
                    },
                },
                ["level"] = 0,
            },
            [4] = {
                ["level"] = 1,
                ["type"] = "WGroupWS",
                ["name"] = "*scratchws*",
                ["pseudomodal"] = true,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1366,
                    ["h"] = 768,
                },
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["geom"] = {
                            ["y"] = 205,
                            ["x"] = 278,
                            ["w"] = 714,
                            ["h"] = 238,
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*",
                        ["bottom"] = true,
                        ["level"] = 1025,
                        ["mode"] = 0,
                        ["managed"] = {
                            [1] = {
                                ["type"] = "WGroupCW",
                                ["name"] = "WGroupCW",
                                ["hidden"] = true,
                                ["geom"] = {
                                    ["y"] = 14,
                                    ["x"] = 4,
                                    ["w"] = 706,
                                    ["h"] = 220,
                                },
                                ["sizepolicy"] = "full",
                                ["managed"] = {
                                    [1] = {
                                        ["type"] = "WClientWin",
                                        ["bottom"] = true,
                                        ["windowid"] = 12582921,
                                        ["checkcode"] = 2,
                                        ["sizepolicy"] = "full",
                                        ["geom"] = {
                                            ["y"] = 0,
                                            ["x"] = 0,
                                            ["w"] = 706,
                                            ["h"] = 220,
                                        },
                                        ["level"] = 1,
                                    },
                                },
                                ["level"] = 0,
                            },
                            [2] = {
                                ["type"] = "WGroupCW",
                                ["name"] = "WGroupCW<1>",
                                ["hidden"] = true,
                                ["geom"] = {
                                    ["y"] = 14,
                                    ["x"] = 4,
                                    ["w"] = 706,
                                    ["h"] = 220,
                                },
                                ["sizepolicy"] = "full",
                                ["managed"] = {
                                    [1] = {
                                        ["type"] = "WClientWin",
                                        ["bottom"] = true,
                                        ["windowid"] = 14680073,
                                        ["checkcode"] = 3,
                                        ["sizepolicy"] = "full",
                                        ["geom"] = {
                                            ["y"] = 0,
                                            ["x"] = 0,
                                            ["w"] = 706,
                                            ["h"] = 220,
                                        },
                                        ["level"] = 1,
                                    },
                                },
                                ["level"] = 0,
                            },
                            [3] = {
                                ["type"] = "WGroupCW",
                                ["name"] = "WGroupCW<3>",
                                ["geom"] = {
                                    ["y"] = 14,
                                    ["x"] = 4,
                                    ["w"] = 706,
                                    ["h"] = 220,
                                },
                                ["switchto"] = true,
                                ["sizepolicy"] = "full",
                                ["managed"] = {
                                    [1] = {
                                        ["type"] = "WClientWin",
                                        ["bottom"] = true,
                                        ["windowid"] = 18874377,
                                        ["checkcode"] = 4,
                                        ["sizepolicy"] = "full",
                                        ["geom"] = {
                                            ["y"] = 0,
                                            ["x"] = 0,
                                            ["w"] = 706,
                                            ["h"] = 220,
                                        },
                                        ["level"] = 1,
                                    },
                                },
                                ["level"] = 0,
                            },
                            [4] = {
                                ["type"] = "WGroupCW",
                                ["name"] = "WGroupCW<2>",
                                ["hidden"] = true,
                                ["geom"] = {
                                    ["y"] = 14,
                                    ["x"] = 4,
                                    ["w"] = 706,
                                    ["h"] = 220,
                                },
                                ["sizepolicy"] = "full",
                                ["managed"] = {
                                    [1] = {
                                        ["type"] = "WClientWin",
                                        ["bottom"] = true,
                                        ["windowid"] = 16777225,
                                        ["checkcode"] = 5,
                                        ["sizepolicy"] = "full",
                                        ["geom"] = {
                                            ["y"] = 0,
                                            ["x"] = 0,
                                            ["w"] = 706,
                                            ["h"] = 220,
                                        },
                                        ["level"] = 1,
                                    },
                                },
                                ["level"] = 0,
                            },
                        },
                        ["sizepolicy"] = "free_glue",
                    },
                },
                ["unnumbered"] = true,
            },
        },
    },
}

