-- This file has been generated by Ion. Do not edit.
return {
    [1] = "menu.mainmenu:session/save",
    [2] = "yesno:y",
    [3] = "menu.mainmenu:styles/look_candymouse",
    [4] = "run:gcolor2",
    [5] = "run:firefox-nightly",
    [6] = "yesno:n",
    [7] = "menu.mainmenu:styles/look_ghostcandy",
    [8] = "yesno:",
    [9] = "workspacelayout:1x2",
    [10] = "workspacename:3.BROWSE",
    [11] = "workspacelayout:",
    [12] = "workspacename:2.TEMP",
    [13] = "framename:1.WORK",
    [14] = "menu.ctxmenu:workspace/rename",
}

