#!/bin/zsh

# global variables:
FN='-*-fixed-*-*-*-*-10-*-*-*-*-*-*-*'
BG="#161616"
FG="#8c8b8e"
H=12
Y=0

# musca groups:
_left() {
W=180
X=0
while true; do
  ws=`musca -c "silent show groups" 2>/dev/null | awk -v ORS="^fg(#0c6389)^bg(#161616)|" '{ print ($2=="*"?"^fg(#6a588d)^bg(#161616)":"^fg(#5f656b)^bg(#161616)")$3}'`
  print "$ws"
done | dzen2 -ta 'l' -h $H -tw $W -x $X -y $Y -fg $FG -bg $BG -fn $FN -e &
}

# system info, etc:
_middle() {
W=446
X=180
while true; do
  echo " ^fg(#6a588d)#^fg(#777)$(lsw|awk ' !x[$0]--'|grep -v "musca\|GLiv\|Vimperator\| - Downloads"|wc -l) ^fg(#007b8c)| \
^fg()$(cat /proc/loadavg|sed 's/ [0-9]\/.*$//;s/\./'"^fg(#5f656b)"'&'"^fg()"'/g') ^fg(#007b8c)| ^fg()\
$(df -h|grep "sda2\|sda5\|sda3"|awk '{print "^fg(#5f656b)"$4"^fg(#050505)""""|^fg(#444)"$5" "}'|tr -d '\n')"\
"^fg(#007b8c)| ^fg(#515056)@fea.st: ^fg()$(ls -1 /home/milo/mail/FastMail/*/new|sed 's|/.*$||'|tr '\n' ' '|wc -w)" \
"^fg() ^fg(#a488d9)>""^fg(#007b8c)>""^fg(#444444)>"
  sleep 1
done | dzen2 -u -x $X -w $W -y $Y -h $H -ta 'l' -bg $BG -fg $FG -fn $FN &
}

# media/date:
_right() {
W=740
X=626
while true; do
  echo "$(mossrat -x)^fg(#a488d9) | ^fg($FG)$(date '+%Y^fg(#444).^fg()%m^fg(#444).^fg()%d^fg(#007b8c)/^fg(#5f656b)%j ^fg(#a488d9)| ^fg()%H^fg(#444):^fg()%M^fg(#444):^fg()%S') "
  sleep 1
done | dzen2 -u -x $X -y $Y -h $H -w $W -ta 'r' -bg $BG -fg $FG -fn $FN &
}

_left
_middle
_right
