#!/bin/zsh
# milomouse <vincent[at]fea.st>
# NOTE: simple bookmark loader for uzbl. uses ratpoison.

# where the bookmarks file is located:
marks=${XDG_DATA_HOME}/uzbl/bookmarks
[[ ! -f $marks ]] || touch $marks

# fix the display in ratpoison's echo:
nmbr=$(wc $marks|awk '{print $1}')
ratp=$(ratpoison -c "echo $(cat -n $marks|tr ' ' '!'|cut -c5-100|awk '{print $1" - "$2}'|tr '!' ' '|head -$nmbr)")
sleep 5

# select bookmark item by line number. don't try to open if [Esc] or number greater than $nmbr sent:
get=$(ratpoison -c "prompt Type the number of the bookmark you wish to view [1-$nmbr]:")
for i in $get; do
  if [[ $i = "(null)" || $i -gt $nmbr ]]; then
    return
  else
    echo "uri $(<$marks|head -$i|tail -1)" | socat - unix-connect:$5
  fi
done
