#!/bin/zsh
# simple bookmarker for uzbl.

# make sure script only used when uzbl is running.
if (ps -a|grep uzbl-core); then
  bookfile=${XDG_DATA_HOME}/uzbl/bookmarks

# don't try to insert if item already present in $bookfile.
  if (! cat $bookfile|grep "$6" >>/dev/null); then
    echo -e "$6" >> $bookfile
    ratpoison -c "echo Bookmark successful."
  else
    ratpoison -c "echo This URL already bookmarked, quitting operation.."
  fi

# quit uzbl.
fi
