#!/bin/zsh
# extremely simple video downloader using "clive".

# basic variables.
cjar="$XDG_DATA_HOME/uzbl/cookies.txt"
dest="$XDG_DOWNLOAD_DIR"
export CLIVE_CACHE="$XDG_CACHE_HOME"
check_url=$(print "$6"|cut -d "/" -f3|sed 's|\.com.*$||;s|\.de.*$||')

# first check to see if site is supported before sending the script to work.
if [[ ! -n $(clive --hosts|sed '$ d'|awk '{print $1}'|grep $check_url) ]]; then
  ratpoison -c "echo Sorry, this site isn't supported yet."
else
  ratpoison -c "echo Starting download, please wait.."
  clive -qrf best --no-proxy --cookie-jar=$cjar --save-dir=$dest "$url"
  ratpoison -c "echo Download complete."
fi
