#!/bin/zsh
# milomouse <vincent[at]fea.st>
# NOTE: simple script to extract urls from a webpage using w3m.
#       $?: modified from extract.sh

# i removed #'ed links because they generally clutter up display, and are usually links to same page.
url="$6"
temp=$(mktemp)
w3m -dump_source "$url" | grep -Eo "<a[^>]*href=\"([^\"]*)\"[^>]*>" | \
sed -e 's|<a[^>]*href="||g;s|"[^>]*>||g;s|#.*||g' | grep "p:/"  >! $temp
urxvt -e w3m $temp && rm -f $temp
