#!/bin/zsh
# simple script to extract urls from a webpage using w3m. grep/sed from "extract.sh"
# NOTE: this doesn't seem to work properly everytime. will mess with this later.
url="$6"
temp=$(mktemp)
w3m -dump_source "$url" | \
    grep -Eo "<a[^>]*href=\"([^\"]*)\"[^>]*>" | \
    sed -e 's/<a[^>]*href="//g' -e 's/"[^>]*>//g' >! $temp
urxvt -e w3m $temp && rm -f $temp
