#!/bin/zsh
# simple script to extract urls from a webpage using w3m. modified from extract.sh
url="$6"
temp=$(mktemp)
w3m -dump_source "$url" | grep -Eo "<a[^>]*href=\"([^\"]*)\"[^>]*>" | \
sed -e 's|<a[^>]*href="||g;s|"[^>]*>||g;s|#.*||g' | grep "p:/"  >! $temp
urxvt -e w3m $temp && rm -f $temp
