#!/bin/zsh
# simple find prompts for uzbl using ratpoison.

# change value of $1 from config->-*->action.
config=$1; shift
pid=$1;    shift
xid=$1;    shift
fifo=$1;   shift
socket=$1; shift
url=$1;    shift
title=$1;  shift
action=$1

# set 'forward' as default if script ran without options.
if [ "$action" != 'forward' -a  "$action" != 'reverse' ]; then
  $action=forward
fi
if [[ $action = "forward" ]]; then
# search forward/down.
  get=$(ratpoison -c "prompt Find Forward:")
    for i in $get; do
      if [[ $i = "(null)" ]]; then
        return
      else
        echo "search $i" | socat - unix-connect:$socket
      fi
    done
else
  if [[ $action = "reverse" ]]; then
# search reverse/up.
  get=$(ratpoison -c "prompt Find Reverse:")
    for j in $get; do
      if [[ $j = "(null)" ]]; then
        return
      else
        echo "search_reverse $j" | socat - unix-connect:$socket
      fi
    done
  fi
fi
