#!/bin/zsh
# simple history loader for uzbl using ratpoison.
# TODO: head/tail based on length. repeat $math until $nmbr -le X
#    ^: if ROWS instead of COLUMNS, truncate length of display.
#    ^: find better $ratp; no need for cat -n, or cut and tr.

# make sure script only used when uzbl is running.
if (ps -a|grep uzbl-core); then
  histfile=${XDG_DATA_HOME}/uzbl/history

# do not execute if only item found is current, else execute.
  if [[ $(awk ' !x[$0]--' <$histfile) = "$6" ]]; then
    ratpoison -c "echo Current URL is only item in history, quitting operation.."
  else
    nmbr=$(wc $histfile|awk '{print $1}')
    ratp=$(ratpoison -c "echo $(cat -n $histfile|tr ' ' '!'|cut -c5-100|awk '{print $1" - "$2}'|tr '!' ' '|head -$nmbr)")
    sleep 5

# select history item by line number. don't try to open if [Esc] or empty string is sent.
    get=$(ratpoison -c "prompt Type the number of the history item you wish to view [1-$nmbr]:")
    for i in $get; do
      if [[ $i = "(null)" || $i -gt $nmbr ]]; then
        ratpoison -c "echo Nothing selected, quitting operation.."
      else
        echo "uri $(<$histfile|head -n $i|tail -1)" | socat - unix-connect:$5
      fi
    done
  fi
#quit uzbl.
fi
