#!/bin/zsh
# simple history inserter for uzbl using fifos and ratpoison.
# TODO: find better fix for duplicates, especially http://{www.}$.com{/}

# make sure script only used when uzbl is running.
if (ps -a|grep uzbl-core); then
  histfile=${XDG_DATA_HOME}/uzbl/history
  fifo_in=${XDG_CACHE_HOME}/uzbl/history_in
  fifo_out=${XDG_CACHE_HOME}/uzbl/history_out

# only create $histfile if there is none. always cleanse fifos.
  [[ -f $histfile ]] || touch $histfile
  rm -f $fifo_in $fifo_out && mkfifo -m 600 $fifo_in $fifo_out

# use fifos to redirect $hsitfile directly back on itself while truncating and appending,
# but do not write item if last entry of $histfile is same as current, as with reloads.
  if [[ ! $(sed '$ !d' <$histfile) = "$6"/ || ! $(sed '$ !d' <$histfile) = "$6" || \
! $(expr "$6"|sed "s|tp://|tp://www.|") = "$6" || ! $(expr "$6"/|sed "s|tp://|tp://www.|") = "$6" ]]; then
    tail -51 < $fifo_out < $fifo_in >! $histfile &
    cat $histfile|awk ' !x[$0]--' >> $fifo_out
    expr "$6" >> $fifo_in
  fi

# quit uzbl.
fi
