#!/bin/zsh
# jump to frequently used urls by assigning numbers 0-9 to each one.

# change value of $1 from config->-*->action.
config=$1; shift
pid=$1;    shift
xid=$1;    shift
fifo=$1;   shift
socket=$1; shift
url=$1;    shift
title=$1;  shift
action=$1

# where to save the quickjump links:
savefile=$XDG_DATA_HOME/uzbl/quicklinks
tempfile=$XDG_CACHE_HOME/uzbl/.tmpqj

# create initial file with 10 lines:
hidden() {
  until [[ $(wc -l $savefile|awk '{print $1}') = 10 ]]; do
    print "http://uzbl.org" >> $savefile
  done
}
if [[ ! -f $savefile ]]; then
  touch $savefile
  hidden
#elif [[ $(wc -c $savefile|awk '{print $1}') = "0" ]]; then
#  rm -f $savefile && touch $savefile
#  hidden
fi

# show quickjumps for whatever reason:
show_jumps() {
  rm -f $tempfile >&/dev/null && touch $tempfile
  hidden
  ratpoison -c "echo $(<$savefile|cat -n|tr ' ' '!'|cut -c5-100|awk '{print $1" - "$2}'|tr '!' ' ')"
}

# place current uri into certain line by number:
quick_set() {
  get=$(ratpoison -c "prompt Enter Value for this Jump [0-9]:")
  for i in $get; do
    if [[ $i = "(null)" ]]; then
      exit
    elif [[ $i -gt 9 ]]; then
      ratpoison -c "echo Value too high."
      exit
    elif [[ $i = "0" ]]; then
      i="10"
      rm -f $tempfile >&/dev/null && touch $tempfile
      <$savefile|sed ''"$i"' s|.*$|'"$url"'|'> $tempfile >! $savefile
      rm -f $tempfile >&/dev/null
      exit
    else
      rm -f $tempfile >&/dev/null && touch $tempfile
      <$savefile|sed ''"$i"' s|.*$|'"$url"'|'> $tempfile >! $savefile
      rm -f $tempfile >&/dev/null
      exit
    fi
  done
}

# find a better way to do this:
go1() { print uri "$(<$savefile|head -1|tail -1)" | socat - unix-connect:$socket >&/dev/null }
go2() { print uri "$(<$savefile|head -2|tail -1)" | socat - unix-connect:$socket >&/dev/null }
go3() { print uri "$(<$savefile|head -3|tail -1)" | socat - unix-connect:$socket >&/dev/null }
go4() { print uri "$(<$savefile|head -4|tail -1)" | socat - unix-connect:$socket >&/dev/null }
go5() { print uri "$(<$savefile|head -5|tail -1)" | socat - unix-connect:$socket >&/dev/null }
go6() { print uri "$(<$savefile|head -6|tail -1)" | socat - unix-connect:$socket >&/dev/null }
go7() { print uri "$(<$savefile|head -7|tail -1)" | socat - unix-connect:$socket >&/dev/null }
go8() { print uri "$(<$savefile|head -8|tail -1)" | socat - unix-connect:$socket >&/dev/null }
go9() { print uri "$(<$savefile|head -9|tail -1)" | socat - unix-connect:$socket >&/dev/null }
go0() { print uri "$(<$savefile|head -10|tail -1)"| socat - unix-connect:$socket >&/dev/null }

# in case a typo or something is passed in the config:
error() {
  ratpoison -c "echo Error: Unknown option."
  exit 1
}

case "$action" in
  'show') show_jumps ;;
  'set') quick_set ;;
  'go1') go1 ;;
  'go2') go2 ;;
  'go3') go3 ;;
  'go4') go4 ;;
  'go5') go5 ;;
  'go6') go6 ;;
  'go7') go7 ;;
  'go8') go8 ;;
  'go9') go9 ;;
  'go0') go0 ;;
  * ) error ;;
esac
