#!/bin/zsh
# simple search prompts for uzbl using surfraw and ratpoison.

get=$(ratpoison -c "prompt Enter search mechanism to use [L for list]:")
for i in $get; do
  if [[ $i = "(null)" || $i = " " ]]; then
    ratpoison -c "echo Nothing selected, quitting operation.."
  else
    if [[ $i = "L" || $i = "list" ]]; then
      ratpoison -c "echo $(surfraw -elvi|awk '{print $1}'|sed '50,$ d')"
      sleep 5
      ratpoison -c "echo $(surfraw -elvi|awk '{print $1}'|sed '50,$ !d')"
      sleep 5
    fi
    if [[ $i = "L" || $i = "list" ]]; then
      return
    fi
    if [[ ! $i = $(surfraw -elvi|awk '{print $1}'|grep $i) ]]; then
      ratpoison -c "echo Sorry, $i doesn't appear to be a valid mechanism."
    else
      key=$(ratpoison -c "prompt $i:")
      for word in $key; do
        if [[ $word = "(null)" || $word = " " ]]; then
          ratpoison -c "echo Nothing selected, quitting operation.."
        else
          echo "uri `surfraw -browser=echo $i $word`" | socat - unix-connect:$5
        fi
      done
    fi
  fi
done
