#!/bin/zsh
# milomouse <vincent[at]fea.st>
# NOTE: simple search prompts for uzbl using surfraw. uses ratpoison.

get=$(ratpoison -c "prompt Enter search mechanism to use [L for list]:")
for i in $get; do
  if [[ $i = "(null)" ]]; then
    return
  else
    if [[ $i = [lL] || $i = "list" ]]; then
      # thankfully there's only 103 right now. yes, these sed lines are correct.
      ratpoison -c "echo $(surfraw -elvi|awk '{print $1}'|sed '52,$ d')"
      sleep 5
      ratpoison -c "echo $(surfraw -elvi|awk '{print $1}'|sed '52,$ !d')"
      sleep 5
      return
    fi
    if [[ ! $i = $(surfraw -elvi|awk '{print $1}'|grep $i) ]]; then
      ratpoison -c "echo Sorry, \"$i\" doesn't appear to be a valid mechanism."
    else
      key=$(ratpoison -c "prompt [$i]:")
      for word in $key; do
        if [[ $word = "(null)" ]]; then
          return
        else
          print "uri `surfraw -browser=echo $i $word`" | socat - unix-connect:$5
        fi
      done
    fi
  fi
done
