#!/bin/zsh
# simple source viewer for uzbl using curl and w3m (which uses vim if you wish to edit)

# set referer until i figure out a "requestpolicy" script. set user-agent because some sites suck.
referer="'http://ixquick.com/do/metasearch.pl?query="$7"'"
uagent="Mozilla/5.0"
output="$(mktemp)"

# junk session cookies, use ixquick as referer, do not redirect to different source, kill after 60s.
curl -sj --raw --user-agent $uagent --ssl -e $referer --max-redirs 0 -m 60 "$6" -o $output && \
urxvt -e w3m $output && rm -f $output
