#! /bin/zsh
##############################################
## locate: ${XDG_CONFIG_HOME}/xorg/xinitrc  ##
## author: Vincent (github.com/milomouse)   ##
## detail: X.Org init configuration file    ##
##############################################

## RESOURCES:
xrandr --setprovidersoutputsource modesetting NVIDIA-0
xrandr --auto
xrdb -load ${XDG_CONFIG_HOME:-$HOME}/xorg/Xresources &

## INPUT:
# xmodmap ${XDG_CONFIG_HOME:-$HOME}/keymaps/zsu.xmodmap &
xmodmap ${XDG_CONFIG_HOME:-$HOME}/keymaps/overlay.xmodmap &
zaprat --disable &

## DISPLAY:
xsetroot -cursor_name left_ptr -solid '#101010' &
display -window root -resize 3840x2160! ${XDG_PUBLICSHARE_DIR}/images/kali-ma-pearl.jpg &

## WINDOW MANAGER:
sxhkd -c ${XDG_CONFIG_HOME:-$HOME}/herbstluftwm/sxhkdrc &
exec herbstluftwm --locked -c ${XDG_CONFIG_HOME:-$HOME}/herbstluftwm/autostart
