#!/bin/zsh
# resources:
/usr/bin/xset +fp '/usr/share/fonts/local'
/usr/bin/xset fp rehash
/usr/bin/xrdb -load ${XDG_CONFIG_DIR:-$HOME}/xorg/Xdefaults
#/usr/bin/xmodmap ${XDG_CONFIG_DIR:-$HOME}/keymaps/dvausler.xmodmap
/usr/bin/xmodmap ${XDG_CONFIG_DIR:-$HOME}/keymaps/overlay-mods.xmodmap

# extras:
/usr/bin/xsetroot -cursor_name left_ptr -solid '#151515'
/usr/bin/display -window root -resize 1600x900! ${XDG_PICTURES_DIR:-${HOME}/foto}/wall/astrolithe.png
/usr/local/bin/zaprat --disable

# window-manager:
export BSPWM_PANEL_FIFO="/tmp/user-keep/${USER}/bspwm-fifo"
/usr/bin/sxhkd -c ${XDG_CONFIG_DIR:-$HOME}/bspwm/sxhkdrc &
exec /howl/conf/bspwm/dzen4bspwm.zsh &
[[ -p ${BSPWM_PANEL_FIFO} ]] && rm ${BSPWM_PANEL_FIFO}
mkfifo ${BSPWM_PANEL_FIFO}
exec /usr/bin/bspwm -s ${BSPWM_PANEL_FIFO}
#exec /usr/bin/herbstluftwm &>${XDG_CONFIG_DIR:-$HOME}/herbstluftwm/log
