#!/bin/zsh
# resources:
xrdb -load ${XDG_CONFIG_DIR:-${HOME}/.config}/xorg/Xdefaults
xsetroot -cursor_name left_ptr &

# keyboard:
xmodmap -e "keycode 133 = Alt_L"
xmodmap -e "keycode 135 = Alt_R"
xmodmap -e "keycode 64 = Super_L"
xmodmap -e "keycode 108 = Super_R"
xmodmap -e "clear Mod1"
xmodmap -e "clear Mod4"
xmodmap -e "add Mod1 = Alt_L Alt_R"
xmodmap -e "add Mod4 = Super_L Super_R"

# mouse/synclient:
_file="/dev/shm/cache/.banishmouse"
[ ! -f $_file ] || rm -f $_file
banishmouse

# wallpaper:
display -window root -resize 1366x768! \
  ${XDG_PICTURES_DIR:-${HOME}/foto}/wall/1366x768_Dizorb_Landscape_Study_HD_Wallpaper.png
#  ${XDG_PICTURES_DIR:-${HOME}/foto}/wall/1366x768-Dizorb-Breakdown-The-Space-HD-Wallpaper.png
#  ${XDG_PICTURES_DIR:-${HOME}/foto}/wall/1366x768_Dizorb_Landscape_Study_HD_Wallpaper.png
#  ${XDG_PICTURES_DIR:-${HOME}/foto}/wall/1366x768-Dizorb-The-Homeworld-HD-Wallpaper.png
#  ${XDG_PICTURES_DIR:-${HOME}/foto}/wall/wallpaper-249719.png

# window-manager:
exec stumpwm &>/dev/null
