#!/bin/zsh
# resources:
xrdb -load ${XDG_CONFIG_DIR:-${HOME}/.config}/xorg/Xdefaults
xsetroot -cursor_name left_ptr &

# keyboard:
xmodmap -e "keycode 133 = Alt_L"
xmodmap -e "keycode 135 = Alt_R"
xmodmap -e "keycode 64 = Super_L"
xmodmap -e "keycode 108 = Super_R"
xmodmap -e "clear Mod1"
xmodmap -e "clear Mod4"
xmodmap -e "add Mod1 = Alt_L Alt_R"
xmodmap -e "add Mod4 = Super_L Super_R"

# mouse/synclient:
_file="/dev/shm/.1000/banishmouse"
[[ ! -f $_file ]] || rm -f $_file
banishmouse

# for the holidays:
xsnow -notrees -nosanta -norudolf -nokeepsnow -nokeepsnowonwindows -nokeepsnowonscreen &>/dev/null &

# wallpaper:
display -window root -resize 1366x768! ${XDG_PICTURES_DIR:-${HOME}/foto}/wall/wallpaper-822124.png

# window-manager:
exec stumpwm &>>${XDG_CONFIG_DIR:-${HOME}/.config}/stumpwm/logfile
