#!/usr/bin/env bash
#######################################################
## locate: ${XDG_CONFIG_HOME}/herbstluftwm/autostart ##
## author: Vincent (github.com/milomouse)            ##
## detail: startup file for `herbstluftwm'           ##
#######################################################

# function shortcut
hc() {
  herbstclient "$@"
}

# reload and reset
hc emit_hook reload
hc keyunbind --all

# modifier key
Mod=Mod4

# define tags and associated keys
# secondary monitor always assigned to the second tag,
# so we change the order of tag/index to be more coherent once created
tag_names=( I X II III IV V VI VII)
tag_keys=( 1 0 {2..7} )

# frame layout (always prefer one frame by default)
hc set default_frame_layout 2
hc set_layout max

# automatically assign keybindings to appropriate tag
hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
  hc add "${tag_names[$i]}"
  key="${tag_keys[$i]}"
  if ! [ -z "$key" ] ; then
    hc keybind "$Mod-$key" use_index "$i"
    hc keybind "$Mod-Shift-$key" move_index "$i"
  fi
done

# mouse/pointer related
hc mouseunbind
hc mousebind $Mod-B1 move
hc mousebind $Mod-B2 resize
hc mousebind $Mod-B3 zoom
hc set focus_follows_mouse 0

# theme attributes
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc attr theme.floating.border_width 13
hc attr theme.floating.outer_width 0
hc attr theme.border_width 13
hc attr theme.inner_width 0
hc attr theme.outer_width 0
hc attr theme.inner_color '#080808'
hc attr theme.active.inner_color '#292929'
hc attr theme.normal.inner_color '#080808'
hc attr theme.outer_color '#292929'
hc attr theme.active.outer_color '#616161'
hc attr theme.normal.outer_color '#080808'
hc attr theme.active.color '#262626'
# hc attr theme.active.color '#292929'
# hc attr theme.active.color '#313238'
hc attr theme.normal.color '#161616'
# hc attr theme.normal.color '#121212'
# hc attr theme.normal.color '#1E1E21'
hc attr theme.urgent.color '#FF009A'
hc attr theme.background_color '#101010'

# theme settings
hc set show_frame_decorations if_multiple
hc set frame_bg_transparent 1
hc set frame_bg_active_color '#616161'
hc set frame_bg_normal_color '#101010'
hc set frame_border_active_color '#444444'
hc set frame_border_normal_color '#1E1E21'
hc set frame_border_inner_color '#080808'
hc set frame_border_inner_width 0
hc set frame_border_width 1
hc set frame_gap 0
hc set frame_padding 0
hc set frame_transparent_width 0
hc set mouse_recenter_gap 0
hc set smart_frame_surroundings 0
hc set smart_window_surroundings 0
hc set window_gap 0

# monitor settings
# make sure we don't cycle between monitors unless we explicitly select the tags
hc set swap_monitors_to_get_tag false
hc set focus_crosses_monitor_boundaries false

# ASCII graph for layout command
hc set tree_style '·│ ├└+─┐'

# rules
# unset any previously assigned rules
hc unrule -F

# non-tag specific rules;
hc rule focus=on
hc rule class="a.out" floating=on
hc rule class="Toplevel" pseudotile=on
# hc rule class="Dialog" pseudotile=on
hc rule class="polybar" manage=off
hc rule class="mpv" pseudotile=off
hc rule class="Nvidia-settings" floating=on
hc rule class="sun-awt-X11-XFramePeer" pseudotile=on
hc rule class~'(.*[yY]ad)' floating=on
hc rule class~'(.*[pP]qiv)' pseudotile=on
# hc rule title="Open File" floating=on
# hc rule title="Open Image" pseudotile=on
# hc rule title="Save As" pseudotile=on
# hc rule title="Save file" pseudotile=on
# hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' focus=on pseudotile=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# tag I (default);

# tag II (debugging);

# tag III (complementary);
hc rule class="Godot" tag=III

# tag IV (literature);
hc rule class="calibre" tag=IV

# tag V (gaming);
hc rule class="duckstation-nogui" tag=V
hc rule class="retroarch" tag=V
hc rule class~'(.*[pP]csx2)' tag=V pseudotile=on
hc rule class~'(.*[eE]u4)' tag=V
hc rule class~'(.*[sS]lime [rR]ancher)' tag=V
hc rule class~'(.*[fF]actorio)' tag=V
hc rule class~'(.*[rR]im[wW]orld[lL]inux)' tag=V

# tag VI (illustration);
hc rule class~'(.*[kK]rita)' tag=VI
hc rule class~'(.*[gG]imp)' tag=VI
hc rule class~'(.*[iI]nkscape)' tag=VI
hc rule class~'(.*[mM]y[pP]aint)' tag=VI
hc rule class~'(.*[sS]ubstance-[pP]ainter)' tag=VI

# tag VII (3D modeling);
hc rule class~'(.*[bB]lender)' tag=VII

# tag X ([second monitor]);
# search the herbstluftwm manpage for "FRAME INDEX"
hc rule class~'(.*[fF]irefox)' tag=X index=0
hc rule class~'(.*[nN]avigator)' tag=X index=0
hc rule class~'(.*[sS]potify)' tag=X index=1
hc rule class~'(.*[dD]iscord)' tag=X index=1
hc rule class~'(.*[pP]ure[rR]ef)' tag=X fullscreen=off index=e
hc rule class="obs" tag=X index=e
hc rule class="LM Studio" tag=X index=0

# reset monitors_locked uint, just to be sure
# if monitors_locked is changed to 0, then all monitors are repainted again
hc unlock

# run commands on initial loading of this autostart file
# we do not want these commands ran when herbstluftwm is reloaded
# NOTE: custom attribute must begin with: my_
if hc silent new_attr bool my_autostart_sanity_check ; then
  # second monitor has scaling applied via 'xrandr' within xinitrc file
  # re-adjust size for correct boundaries within herbstluftwm
  hc set_monitors 3840x2160+2016+0 2016x3584+0+0

  # rename monitors for possible script integration
  hc rename_monitor 0 "ViewSonic"
  hc rename_monitor 1 "BenQ"

  # lock second monitor from switching tags ("use" and "use_index")
  hc lock_tag BenQ

  # setup default frames for second monitor
  # hc load X '(split vertical:0.61:0)'

  # example: run external programs if desired
  # spotify &
fi

# panel (restart 'polybar' if already running)
polybar-msg cmd quit 2>&1
polybar -c ${XDG_CONFIG_HOME}/polybar/config.ini main 2>&1 & disown
