#!/usr/bin/env bash
#######################################################
## locate: ${XDG_CONFIG_HOME}/herbstluftwm/autostart ##
## author: Vincent (github.com/milomouse)            ##
## detail: startup file for `herbstluftwm'           ##
#######################################################

hc() {
  herbstclient "$@"
}

hc emit_hook reload
hc keyunbind --all

Mod=Mod1

tag_names=( I II III IV V VI )
tag_keys=( {1..6} )

hc set default_frame_layout 2
hc set_layout max

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
  hc add "${tag_names[$i]}"
  key="${tag_keys[$i]}"
  if ! [ -z "$key" ] ; then
    hc keybind "$Mod-$key" use_index "$i"
    hc keybind "$Mod-Shift-$key" move_index "$i"
  fi
done

hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 resize
hc mousebind $Mod-Button3 zoom

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc attr theme.floating.border_width 10
hc attr theme.floating.outer_width 0
hc attr theme.border_width 10
hc attr theme.inner_width 0
hc attr theme.outer_width 0
hc attr theme.inner_color '#080808'
hc attr theme.active.inner_color '#292929'
hc attr theme.normal.inner_color '#080808'
hc attr theme.outer_color '#292929'
hc attr theme.active.outer_color '#616161'
hc attr theme.normal.outer_color '#080808'
hc attr theme.active.color '#616161'
hc attr theme.normal.color '#202020'
hc attr theme.urgent.color '#FF009A'
hc attr theme.background_color '#101010'

hc set tree_style '·│ ├└+─┐'
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_bg_active_color '#616161'
hc set frame_bg_normal_color '#101010'
hc set frame_border_active_color '#282C35'
hc set frame_border_normal_color '#1E1E21'
hc set frame_border_inner_color '#080808'
hc set frame_border_inner_width 0
hc set frame_border_width 0
hc set frame_gap 0
hc set frame_padding 0
hc set frame_transparent_width 0
hc set mouse_recenter_gap 0
hc set smart_frame_surroundings 0
hc set smart_window_surroundings 0
hc set window_gap 0
hc set window_border_active_color '#2d2e33'
hc set window_border_normal_color '#1E1E21'
hc set window_border_urgent_color '#FF009A'

hc unrule -F
hc rule focus=on
hc rule class="polybar" manage=off
hc rule class="mpv" pseudotile=off
hc rule class="Toplevel" pseudotile=on
hc rule class="Dialog" pseudotile=on
hc rule class="sun-awt-X11-XFramePeer" pseudotile=on
hc rule class="calibre" tag=II
hc rule class="forge-view-Main" tag=IV
hc rule class="retroarch" tag=IV
hc rule class="duckstation-nogui" tag=IV
hc rule class="PPSSPPSDL" tag=IV
hc rule class="Deep Sky Derelicts.x86_64" tag=IV
hc rule class="KSP.x86_64" tag=IV
hc rule class="Rise of Industry" tag=IV
hc rule class="Space Haven" tag=IV
hc rule class="Civilization6" tag=IV
hc rule class~'(.*[sS]potify)' tag=II
hc rule class~'(.*[dD]iscord)' tag=II
hc rule class~'(.*[fF]irefox)' tag=III
hc rule class~'(.*[nN]avigator)' tag=III
hc rule class~'(.*[fF]actorio)' tag=IV
hc rule class~'(.*[eE]u4)' tag=IV
hc rule class~'(.*[cC]k2)' tag=IV
hc rule class~'(.*[cC]k3)' tag=IV
hc rule class~'(.*[sS]tellaris)' tag=IV
hc rule class~'(.*[iI]mperator)' tag=IV
hc rule class~'(.*[oO]ffworld)' tag=IV
hc rule class~'(.*[rR]im[wW]orld[lL]inux' tag=IV
hc rule class~'(.*[bB]attle[tT]ech)' tag=IV
hc rule class~'(.*[bB]lender)' tag=V
hc rule class~'(.*[sS]ubstance-[pP]ainter)' tag=VI
hc rule class~'(.*[kK]rita)' tag=VI
hc rule class~'(.*[gG]imp)' tag=VI
hc rule class~'(.*[iI]nkscape)' tag=VI
hc rule class~'(.*[pP]ure[rR]ef)' tag=VI
hc rule class~'(.*[sS]xiv)' pseudotile=on
hc rule class~'(.*[yY]ad)' floating=on
hc rule class="Nvidia-settings" floating=on
hc rule title="Open File" floating=on
hc rule title="Open Image" pseudotile=on
hc rule title="Save As" pseudotile=on
hc rule title="Save file" pseudotile=on
hc rule title="Loading Forge..." pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc unlock

# hc pad 0 69 0 0 0
polybar-msg cmd quit
> /tmp/polybar.log
polybar 2>&1 | tee -a /var/tmp/polybar.log & disown
