;; <set "Super + s" as prefix for root-map bindings>
(set-prefix-key (kbd "s-s"))

;; <input-map bindings>
;;(setf *input-map*
;;  (let ((m (stumpwm:make-sparse-keymap)))
;;     (define-key m (kbd "ESC")   "abort")
;;     (define-key m (kbd "w")     "windowlist")
;;     (define-key m (kbd "g")     "vgroups")
;;    M))

;; <groups-map bindings>
;;(setf *groups-map*
;;  (let ((m (stumpwm:make-sparse-keymap)))
;;     (define-key m (kbd "ESC")   "abort")
;;     (define-key m (kbd "w")     "windowlist")
;;     (define-key m (kbd "g")     "vgroups")
;;    M))

;; <commonly toggled options>
(defvar *toggles-map*
  (let ((m (stumpwm:make-sparse-keymap)))
    (define-key m (kbd "s") "mode-line")
    (define-key m (kbd "ESC") "abort")
   M))

;; <frequently used programs>
(defvar *frequent-map*
  (let ((m (stumpwm:make-sparse-keymap)))
    (define-key m (kbd "f") "ror_firefox")
    (define-key m (kbd "m") "exec urxvt -e mutt -F ${XDG_CONFIG_DIR:-${HOME}/.config}/mutt/muttrc")
    (define-key m (kbd "s") "exec urxvt -e nsudoku 12")
    (define-key m (kbd "w") "exec wallie")
    (define-key m (kbd "x") "exec xskat -opt ${XDG_CONFIG_DIR:-${HOME}/.config}/xorg/xskat.opt -list ${XDG_CONFIG_DIR:-${HOME}/.config}/xorg/xskat.lst")
    (define-key m (kbd "ESC") "abort")
   M))

;; <search-engine bindings>
(defvar *websearch-map*
  (let ((m (stumpwm:make-sparse-keymap)))
    (define-key m (kbd "a") "amazon")
    (define-key m (kbd "c") "cliki")
    (define-key m (kbd "d") "deja")
    (define-key m (kbd "e") "ebay")
    (define-key m (kbd "f") "sourceforge")
    (define-key m (kbd "g") "google")
    (define-key m (kbd "i") "imdb")
    (define-key m (kbd "l") "lastfm")
    (define-key m (kbd "o") "codesearch")
    (define-key m (kbd "p") "piratebay")
    (define-key m (kbd "r") "aur")
    (define-key m (kbd "s") "slashdot")
    (define-key m (Kbd "w") "wikipedia")
    (define-key m (Kbd "x") "ixsearch")
    (define-key m (kbd "y") "youtube")
  M))

;; <mplayer-daemon-* bindings>
(defvar *mplayer-daemon-map1*
  (let ((m (stumpwm:make-sparse-keymap)))
    (define-key m (kbd "d")     "exec sudo /etc/rc.d/mifo start")
    ;(define-key m (kbd "d")     "exec mifo --daemon")
    (define-key m (kbd "t")     "exec mifo --toggle")
    (define-key m (kbd "r")     "exec mifo --random")
    (define-key m (kbd "j")     "exec mifo --next dir")
    (define-key m (kbd "k")     "exec mifo --prev dir")
    (define-key m (kbd "l")     "exec mifo --next")
    (define-key m (kbd "h")     "exec mifo --prev")
    (define-key m (kbd "L")     "prompt-mifo-next")
    (define-key m (kbd "H")     "prompt-mifo-prev")
    (define-key m (kbd "a")     "prompt-mifo-load")
    (define-key m (kbd "A")     "prompt-mifo-append")
    (define-key m (kbd "p")     "prompt-mifo-playlist")
    (define-key m (kbd "s")     "prompt-mifo-save")
    (define-key m (kbd "S")     "exec mifo --stop")
    (define-key m (kbd "q")     "exec sudo /etc/rc.d/mifo stop")
    ;(define-key m (kbd "q")     "exec mifo --quit")
    (define-key m (kbd "f")     "exec mifo --fullscreen")
    (define-key m (kbd "equal") "exec mifo --fav-add")
    (define-key m (kbd "minus") "exec mifo --fav-delete")
    (define-key m (kbd "ESC")   "abort")
   M))
(defvar *mplayer-daemon-map2*
  (let ((m (stumpwm:make-sparse-keymap)))
    (define-key m (kbd "l")     "exec mifo -c seek 15")
    (define-key m (kbd "C-l")   "exec mifo -c seek 405")
    (define-key m (kbd "h")     "exec mifo -c seek -17")
    (define-key m (kbd "L")     "exec mifo -c seek 45")
    (define-key m (kbd "H")     "exec mifo -c seek -47")
    (define-key m (kbd "C-h")   "exec mifo -c seek -407")
    (define-key m (kbd "!")     "exec mifo -c seek_chapter -1")
    (define-key m (kbd "@")     "exec mifo -c seek_chapter 1")
    (define-key m (kbd "BackSpace") "exec mifo -c seek 0 1")
    (define-key m (kbd "Return")"prompt-mifo-reload")
    (define-key m (kbd "ESC")   "abort")
   M))

;; <top-map bindings>
(setf *top-map*
  (let ((m (stumpwm:make-sparse-keymap)))
    ;; <numerical bindings>
    ;(define-key m (kbd "s-1")    "gview_1")
    ;(define-key m (kbd "s-2")    "gview_2")
    ;(define-key m (kbd "s-3")    "gview_3")
    ;(define-key m (kbd "s-4")    "gview_4")
    ;(define-key m (kbd "s-5")    "gview_5")
    ;(define-key m (kbd "s-6")    "gview_6")
    (define-key m (kbd "s-1")    "gselect 1")
    (define-key m (kbd "s-2")    "gselect 2")
    (define-key m (kbd "s-3")    "gselect 3")
    (define-key m (kbd "s-4")    "gselect 4")
    (define-key m (kbd "s-5")    "gselect 5")
    (define-key m (kbd "s-6")    "gselect 6")
    (define-key m (kbd "s-8")    "clear-window-marks")
    (define-key m (kbd "s-C-8")  "gmove-marked")
    (define-key m (kbd "s-M-8")  "pull-marked")
    (define-key m (kbd "s-9")    "resize -15 0")
    (define-key m (kbd "s-0")    "resize  15 0")
    (define-key m (kbd "C-1")    "select-window-by-number 1")
    (define-key m (kbd "C-2")    "select-window-by-number 2")
    (define-key m (kbd "C-3")    "select-window-by-number 3")
    (define-key m (kbd "C-4")    "select-window-by-number 4")
    (define-key m (kbd "C-5")    "select-window-by-number 5")
    (define-key m (kbd "C-6")    "select-window-by-number 6")
    (define-key m (kbd "C-7")    "select-window-by-number 7")
    (define-key m (kbd "C-8")    "select-window-by-number 8")
    (define-key m (kbd "C-9")    "select-window-by-number 9")
    (define-key m (kbd "C-0")    "select-window-by-number 0")
    ;; <special-char bindings>
    (define-key m (kbd "s-!")    "gmove 1")
    (define-key m (kbd "s-@")    "gmove 2")
    (define-key m (kbd "s-#")    "gmove 3")
    (define-key m (kbd "s-$")    "gmove 4")
    (define-key m (kbd "s-%")    "gmove 5")
    (define-key m (kbd "s-^")    "gmove 6")
    (define-key m (kbd "s-*")    "mark")
    (define-key m (kbd "s-)")    "resize  0  15")
    (define-key m (kbd "s-(")    "resize  0 -15")
    (define-key m (kbd "s--")    "vsplit")
    (define-key m (kbd "s-=")    "hsplit")
    (define-key m (kbd "s-+")    "balance-frames")
    (define-key m (kbd "s-;")    "colon")
    (define-key m (kbd "s-:")    "manpage")
    (define-key m (kbd "s-,")    "gprev")
    (define-key m (kbd "s-<")    "gprev-with-window")
    (define-key m (kbd "s-.")    "gnext")
    (define-key m (kbd "s->")    "gnext-with-window")
    (define-key m (kbd "s-/")    "gother")
    (define-key m (kbd "s-?")    "lastmsg")
    (define-key m (kbd "s-ESC")  "exec banishmouse")
    (define-key m (kbd "s-Tab")  "fother")
    (define-key m (kbd "s-BackSpace")       "fclear")
    (define-key m (kbd "s-S-BackSpace")     "delete-window")
    (define-key m (kbd "s-C-BackSpace")     "kill-window")
    (define-key m (kbd "s-Return")          "exec urxvt -e tmux -f ${XDG_CONFIG_DIR:-${HOME}/.config}/tmux/tmux.conf -L xorg new-session")
    (define-key m (kbd "s-S-Return")        "exec urxvt")
    (define-key m (kbd "s-M-Return")        "exec xdotool mousedown 1 ; xdotool mouseup 1")
    (define-key m (kbd "s-SunPrint_Screen") "exec import -window root ${XDG_PICTURES_DIR:-${HOME}/foto}/shot/$(date +%Y_%m_%d-%H%M%S).png")
    (define-key m (kbd "s-S-Delete")        "exec alock -bg image:=${HOME}/foto/wall/beheading.jpg -cursor glyph -auth pam >&/dev/null")
    ;; <alphabetic bindings>
    (define-key m (kbd "s-a")    *mplayer-daemon-map2*)
    (define-key m (kbd "s-A")    "announce-mifo")
    (define-key m (kbd "s-b")    "redisplay")
    (define-key m (kbd "s-B")    "repack-window-numbers")
    ;(define-key m (kbd "s-B")    "announce-battery")
    (define-key m (kbd "s-c")    "remember")
    (define-key m (kbd "s-C")    "place-existing-windows")
    (define-key m (kbd "s-d")    *mplayer-daemon-map1*)
    (define-key m (kbd "s-D")    "prompt-mifo-command")
    (define-key m (kbd "s-e")    "exec ")
    (define-key m (kbd "s-E")    "eval")
    (define-key m (kbd "s-f")    *frequent-map*)
    (define-key m (kbd "s-F")    "forget")
    (define-key m (kbd "s-g")    "vgroups")
    (define-key m (kbd "s-G")    "grouplist")
    (define-key m (kbd "s-h")    "move-focus left")
    (define-key m (kbd "s-H")    "move-window left")
    (define-key m (kbd "s-C-h")  "exchange-direction left")
    (define-key m (kbd "s-M-h")  "ratrelwarp -7 0")
    (define-key m (kbd "s-i")    "info")
    (define-key m (kbd "s-I")    "list-window-properties")
    (define-key m (kbd "s-j")    "move-focus down")
    (define-key m (kbd "s-J")    "move-window down")
    (define-key m (kbd "s-C-j")  "exchange-direction down")
    (define-key m (kbd "s-M-j")  "ratrelwarp 0 7")
    (define-key m (kbd "s-k")    "move-focus up")
    (define-key m (kbd "s-K")    "move-window up")
    (define-key m (kbd "s-C-k")  "exchange-direction up")
    (define-key m (kbd "s-M-k")  "ratrelwarp 0 -7")
    (define-key m (kbd "s-l")    "move-focus right")
    (define-key m (kbd "s-L")    "move-window right")
    (define-key m (kbd "s-C-l")  "exchange-direction right")
    (define-key m (kbd "s-M-l")  "ratrelwarp 7 0")
    (define-key m (kbd "s-m")    "master-focus")
    (define-key m (kbd "s-M")    "master-swap left")
    (define-key m (kbd "s-C-m")  "master-make")
    (define-key m (kbd "s-n")    "next-in-frame")
    (define-key m (kbd "s-N")    "pull-hidden-next")
    (define-key m (kbd "s-o")    "fullscreen") 
    (define-key m (kbd "s-O")    "only") 
    (define-key m (kbd "s-p")    "prev-in-frame")
    (define-key m (kbd "s-P")    "pull-hidden-previous")
    ;; (define-key m (kbd "s-Q")    "quit")
    (define-key m (kbd "s-Q")    "remquit")
    (define-key m (kbd "s-r")    "iresize")
    (define-key m (kbd "s-R")    "remstart")
    (define-key m (kbd "s-S")    *websearch-map*)
    (define-key m (kbd "s-t")    *toggles-map*)
    (define-key m (kbd "s-T")    "title")
    (define-key m (kbd "s-u")    "undo")
    (define-key m (kbd "s-U")    "fselect")
    (define-key m (kbd "s-v")    "dictionary")
    (define-key m (kbd "s-V")    "dict")
    (define-key m (kbd "s-w")    "echo-frame-windows")
    (define-key m (kbd "s-W")    "windowlist")
    (define-key m (kbd "s-x")    "putsel")
    (define-key m (kbd "s-X")    "getsel")
    (define-key m (kbd "s-y")    "window-send-string")
    (define-key m (kbd "s-Y")    "meta")
    (define-key m (kbd "s-z")    "remove")
    (define-key m (kbd "s-Z")    "remove-split")
    ;; <function-key bindings>
    (define-key m (kbd "XF86AudioRaiseVolume") "exec ossvalt -i 1")
    (define-key m (kbd "XF86AudioLowerVolume") "exec ossvalt -d 1")
    ;;(define-key* (kbd "XF86MonBrightnessUp") "exec moodlight --increase")
    ;;(define-key* (kbd "c-XF86MonBrightnessUp") "exec moodlight --max")
    ;;(define-key* (kbd "XF86MonBrightnessDown") "exec moodlight --decrease")
    (define-key m (kbd "XF86AudioMute") "exec ossvalt -m")
    (define-key m (kbd "s-F1")   "dump-group-to-file ~/.config/stumpwm/storage/group_1")
    (define-key m (kbd "s-F2")   "dump-group-to-file ~/.config/stumpwm/storage/group_2")
    (define-key m (kbd "s-F3")   "dump-group-to-file ~/.config/stumpwm/storage/group_3")
    (define-key m (kbd "s-F4")   "dump-group-to-file ~/.config/stumpwm/storage/group_4")
    (define-key m (kbd "s-F5")   "dump-group-to-file ~/.config/stumpwm/storage/group_5")
    (define-key m (kbd "s-F6")   "dump-group-to-file ~/.config/stumpwm/storage/group_6")
    (define-key m (kbd "s-F8")   "dump-window-placement-rules ~/.config/stumpwm/storage/placement_rules")
    (define-key m (kbd "s-F9")   "dump-screen-to-file ~/.config/stumpwm/storage/screen_data")
    (define-key m (kbd "F1")     "restore-from-file ~/.config/stumpwm/storage/group_1")
    (define-key m (kbd "F2")     "restore-from-file ~/.config/stumpwm/storage/group_2")
    (define-key m (kbd "F3")     "restore-from-file ~/.config/stumpwm/storage/group_3")
    (define-key m (kbd "F4")     "restore-from-file ~/.config/stumpwm/storage/group_4")
    (define-key m (kbd "F5")     "restore-from-file ~/.config/stumpwm/storage/group_5")
    (define-key m (kbd "F6")     "restore-from-file ~/.config/stumpwm/storage/group_6")
    (define-key m (kbd "F8")     "restore-window-placement-rules ~/.config/stumpwm/storage/placement_rules")
    (define-key m (kbd "F9")     "restore-from-file ~/.config/stumpwm/storage/screen_data")
    (define-key m (kbd "F10")    "restore-from-file /home/milo/.config/stumpwm/storage/screen_data_last")
    (define-key m (kbd "C-ESC")  "abort")
    (define-key m (kbd "s-quoteleft") "scratchpad")
   M))

(define-key *root-map* (kbd "h") *help-map*)
