#!/bin/zsh
# milomouse <vincent[at]fea.st>
# NOTE: simple bookmarker for uzbl. uses ratpoison.

# where to store the bookmarks file:
  marks=${XDG_DATA_HOME}/uzbl/bookmarks

# don't try to insert if item already present in $marks:
  if [[ ! -n $(<$marks|grep "$6") ]]; then
  get=$(ratpoison -c "prompt Do you really want to bookmark this page? [y/N]:")
    for i in $get; do
      if [[ $i = [yY] ]]; then
        print "$6" >> $marks
        ratpoison -c "echo Bookmark successful."
      else
        return
      fi
    done
  else
    ratpoison -c "echo This URL is already bookmarked."
  fi
