#!/bin/zsh
# milomouse <vincent[at]fea.st>
# NOTE: simple page downloader using wget. uses ratpoison (only for notifications).
#       $?: sadly, i dont know a "convert" command in curl; that's why wget is used.

url="$6"
dest="$XDG_DOWNLOAD_DIR"
ratpoison -c "echo Downloading page, please wait.."
cd $dest
# believe it or not, this is the friendlier option for downloading, read their wiki:
wget -e robots=off --wait 1 --limit-rate=70K -q --no-proxy --page-requisites \
--convert-links --html-extension --no-parent -l 1 "$url"
ratpoison -c "echo Download complete."
