#!/bin/sh
# author: milomouse <vincent[at]fea.st>
# $Id$
# elvis: googlessl	-- Search the web using Google SSL (https://www.google.com)
. surfraw || exit 1

w3_config_hook () {
    def   SURFRAW_google_results "$SURFRAW_results"
    def   SURFRAW_google_search search
    defyn SURFRAW_google_lucky 0
    def   SURFRAW_google_country us
}

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Surfraw search the web using Google SSL (https://www.google.com)
Local options:
  -results=NUM                  Number of search results returned
                                Default: $SURFRAW_google_results
                                Environment: SURFRAW_google_results
EOF
    w3_global_usage
}

w3_parse_option_hook () {
    opt="$1"
    optarg="$2"
    case "$opt" in
    -results=*) setopt   SURFRAW_google_results "$optarg" ;;
    *) return 1 ;;
    esac
    return 0
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments

# Use SURFRAW_lang if present and the country has not been changed
if test -n "$SURFRAW_lang" -a "$SURFRAW_google_country" = "us"; then
    SURFRAW_google_country="$SURFRAW_lang";
fi

case "$SURFRAW_google_country" in
  af|ag|ai|ar|au|bd|bn|bo|br|bs|bw|by|bz|co|cu|do|ec|eg|et|fj|gi|gt|hk|jm|ly|mt|mx|my|na|nf|ng|ni|np|nz|om|pa|pe|ph|pk|pr|py|qa|sa|sb|sg|sv|tj|tr|tw|ua|ug|uy|vn) domain="com.${SURFRAW_google_country}" ;;
  cr|id|il|in|jp|ke|kh|kr|ls|ma|th|uk|uz|vc|ve|vg|vi|ck|yu|za|zm|zw) domain="co.${SURFRAW_google_country}" ;;
  us) domain="com";;
  *)  domain="$SURFRAW_google_country" ;;
esac

if test -z "$w3_args"; then
    w3_browse_url "https://www.google.${domain}/"
else
    escaped_args=`w3_url_of_arg $w3_args`
		w3_browse_url "https://www.google.${domain}/${SURFRAW_google_search}?q=${escaped_args}&num=${SURFRAW_google_results}"
fi
