#!/bin/sh
#
# AUTHOR: milomouse
#
# DATE: Thu Aug 26 2010
#
# DESC: Elvi to search KickAssTorrents
# elvis: kickass		-- Search KickAssTorrents (www.kickasstorrents.com)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search KickAssTorrents (www.kickasstorrents.com) for torrents
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://www.kickasstorrents.com/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://www.kickasstorrents.com/search/${escaped_args}"
fi
